// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsdkwctlvudnmpcivrel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzZGt3Y3RsdnVkbm1wY2l2cmVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMTIwNjksImV4cCI6MjA3MDg4ODA2OX0.uFWNWeLtAmGv6IX4af6nwUHfFZiNZ3tLZL3xntX9Tks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});